### ISSUE TITLE
Does not work anymore version 1.4

### ISSUE THREAD

**Issue by ghost** [tijayfly/ets-tacc-git#4]
Hello,

I have just spent an afternoon trying to make the autopilot work without success, it activates well (I hear the sound on-tacc.waw) but nothing happens except the emergency braking in a random and useless way.

I tried to change lane but the truck does not move, even the steering is not done.

Do you think you can do an update?

**Comment by tijayfly** [comment]
A lot of the dependencies are long since deprecated. I’ve thrown it up on
GitHub in case anyone wants to pick it up, modernise it and make it more
user friendly, but it’s very much an archived thing for me.

To be honest I was rather hoping someone else would have come up with
something better by now…

**Comment by tijayfly** [comment]
Archiving project, please use default acc + easypilot or lane assist by other developers
